services:
  - type: web
    name: pixel-post
    runtime: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: APP_NAME
        value: Pixel Post
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://pixel-post.onrender.com
      
      # PostgreSQL Neon Configuration
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: ep-tight-surf-a8wjxpjy-pooler.eastus2.azure.neon.tech
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: neondb
      - key: DB_USERNAME
        value: neondb_owner
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSLMODE
        value: require
      - key: DB_STATEMENT_TIMEOUT
        value: 0
      
      # Session Configuration
      - key: SESSION_DRIVER
        value: database
      - key: SESSION_SECURE_COOKIE
        value: true
      - key: SESSION_HTTP_ONLY
        value: true
      - key: SESSION_SAME_SITE
        value: lax
      
      # Filesystem Configuration
      - key: FILESYSTEM_DISK
        value: local
      
      # Cache Configuration
      - key: CACHE_STORE
        value: database
      
      # Queue Configuration
      - key: QUEUE_CONNECTION
        value: database
      
      # Mail Configuration
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_PORT
        value: 465
      - key: MAIL_FROM_ADDRESS
        value: noreply@pixel-post.onrender.com
      - key: MAIL_FROM_NAME
        value: Pixel Post